Style/FileName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'tmp/**/*'

Documentation:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 12

Metrics/AbcSize:
  Max: 20.35

Style/FormatString:
  Enabled: false

Metrics/LineLength:
  Max: 125

Metrics/ModuleLength:
  CountComments: false
  Max: 100

Metrics/CyclomaticComplexity:
  # http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/CyclomaticComplexity
  Max: 6

Metrics/PerceivedComplexity:
  # http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/PerceivedComplexity
  Max: 7

Metrics/ClassLength:
  CountComments: false
  Max: 100

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
